import { color } from "framer-motion";

const data = {
  products: [
    {
      id: 1,
      name: "Basic Tee",
      href: "#",
      imageSrc:
        "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-01.jpg",
      imageAlt: "Front of men's Basic Tee in black.",
      price: "$35",
      color: "Black",
      slug: "basic-tree",
      countInStock: 4,
    },
    {
      id: 2,
      name: "White tea",
      href: "#",
      imageSrc:
        "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-02.jpg",
      imageAlt: "Front of men's Basic Tee in white.",
      price: "$35",
      color: "Aspen White",
      slug: "white-tea",
      countInStock: 2,
    },
    {
      id: 3,
      name: "Dark",
      href: "#",
      imageSrc:
        "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-03.jpg",
      imageAlt: "Front of men's Basic Tee in dark gray.",
      price: "$35",
      color: "Charcoal",
      slug: "charcoal",
      countInStock: 8,
    },
    {
      id: 4,
      name: "Artwork Tee",
      href: "#",
      imageSrc:
        "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-04.jpg",
      imageAlt:
        "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
      price: "$35",
      color: "Iso Dots",
      slug: "artwork-tee",
      countInStock: 0,
    },
    {
      id: 5,
      name: "Nike Slim Shirt",
      href: "#",
      imageSrc: "../src/assets/images/p1.jpg",
      imageAlt:
        "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
      price: "$75",
      color: "Iso Dots",
      slug: "nike-slim-shirt",
      countInStock: 101,
    },
    {
      id: 6,
      name: "Adidas Fit Pant",
      href: "#",
      imageSrc: "../src/assets/images/p2.jpg",
      imageAlt:
        "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
      price: "$29",
      color: "Iso Dots",
      slug: "adidas-fit-pant",
      countInStock: 17,
    },
    {
      id: 7,
      name: "Gorno shoe",
      href: "#",
      imageSrc: "../src/assets/images/p3.jpg",
      imageAlt:
        "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
      price: "$34",
      color: "Iso Dots",
      slug: "gorno-shoe",
      countInStock: 29,
    },
    {
      id: 8,
      name: "Shirt 1",
      href: "#",
      imageSrc: "../src/assets/images/shirt1.png",
      imageAlt:
        "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
      price: "$43",
      color: "Iso Dots",
      slug: "shirt-1",
      countInStock: 0,
    },
    {
      id: 9,
      name: "Shirt 2",
      href: "#",
      imageSrc: "../src/assets/images/shirt2.png",
      imageAlt:
        "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
      price: "$89",
      color: "Iso Dots",
      slug: "shirt-2",
      countInStock: 1,
    },
    {
      id: 10,
      name: "Shirt 3",
      href: "#",
      imageSrc: "../src/assets/images/shirt3.png",
      imageAlt:
        "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
      price: "$30",
      color: "Iso Dots",
      slug: "shirt-3",
      countInStock: 0,
    },
    {
      id: 11,
      name: "Trouser 1",
      href: "#",
      imageSrc: "../src/assets/images/trouser1.png",
      imageAlt:
        "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
      price: "$57",
      color: "Iso Dots",
      slug: "trouser-1",
      countInStock: 47,
    },
    {
      id: 12,
      name: "Trouser 2",
      href: "#",
      imageSrc: "../src/assets/images/trouser2.png",
      imageAlt:
        "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
      price: "$49",
      color: "Iso Dots",
      slug: "trouser-2",
      countInStock: 13,
    },
    {
      id: 13,
      name: "Shirt 4",
      href: "#",
      imageSrc: "../src/assets/images/shirt4.png",
      imageAlt:
        "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
      price: "$28",
      color: "Iso Dots",
      slug: "shirt-4",
      countInStock: 0,
    },
    {
      id: 14,
      name: "p 4",
      href: "#",
      imageSrc: "../src/assets/images/p4.jpg",
      imageAlt:
        "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
      price: "$28",
      color: "Iso Dots",
      slug: "p-4",
      countInStock: 201,
    },
  ],
};

// const products = [
//   {
//     id: 1,
//     name: 'Basic Tee',
//     href: '#',
//     imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-01.jpg',
//     imageAlt: "Front of men's Basic Tee in black.",
//     price: '$35',
//     color: 'Black',
//   },
//   {
//     id: 2,
//     name: 'Basic Tee',
//     href: '#',
//     imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-02.jpg',
//     imageAlt: "Front of men's Basic Tee in white.",
//     price: '$35',
//     color: 'Aspen White',
//   },
//   {
//     id: 3,
//     name: 'Basic Tee',
//     href: '#',
//     imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-03.jpg',
//     imageAlt: "Front of men's Basic Tee in dark gray.",
//     price: '$35',
//     color: 'Charcoal',
//   },
//   {
//     id: 4,
//     name: 'Artwork Tee',
//     href: '#',
//     imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-04.jpg',
//     imageAlt: "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
//     price: '$35',
//     color: 'Iso Dots',
//   },

export default data;
