

const data = {
  products: [
    {
      name: "Basic Tee",
      slug: "basic-tee",
      category: "Shirts",
      image: "../src/assets/images/p1.jpg",
      price: 90,
      countInStock: 5,
      brand: 'Tea',
      rating: 3,
      numReviews: 102,
      description: "high quality shirt",
    },
      {
      name: "Nike slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-01.jpg",
      price: 65,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 201,
      description: "exquisite shirt",
    },
      {
      name: "Adidas juggers",
      slug: "adidas-juggers",
      category: "Troussers",
      image: "../src/assets/images/p2.jpg",
      price: 29,
      countInStock: 100,
      brand: 'Adidas',
      rating: 5,
      numReviews: 307,
      description: "Expandable trouser",
    },
    // {
    //   name: "Basic Tee",
    //   href: "#",
    //   imageSrc:
    //     "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-02.jpg",
    //   imageAlt: "Front of men's Basic Tee in white.",
    //   price: 20,
    //   color: "Aspen White",
    //   rating: 3,
    //   numReviews: 102,
    //   countInStock: 8,
    //   slug: "basic-tee",
    // },
    // {
    //         name: "Basic Tee",
    //   href: "#",
    //   imageSrc:
    //     "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-03.jpg",
    //   imageAlt: "Front of men's Basic Tee in dark gray.",
    //   price: 39,
    //   color: "Charcoal",
    //   rating: 3,
    //   numReviews: 102,
    //   countInStock: 0,
    //   slug: "basic-tee",
    // },
    // {
    //         name: "Artwork Tee",
    //   href: "#",
    //   imageSrc:
    //     "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-04.jpg",
    //   imageAlt:
    //     "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
    //   price: 43,
    //   color: "Iso Dots",
    //   rating: 3,
    //   numReviews: 23,
    //   countInStock: 9,
    //   slug: "artwork-tee",
    // },
    // {
    //         name: "Nike Slim Shirt",
    //   href: "#",
    //   imageSrc: "../src/assets/images/p1.jpg",
    //   imageAlt:
    //     "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
    //   price: 101,
    //   color: "Iso Dots",
    //   rating: 3,
    //   numReviews: 23,
    //   countInStock: 110,
    //   slug: "nike-slim-shirt",
    // },
    // {
    //         name: "Adidas Fit Pant",
    //   href: "#",
    //   imageSrc: "../src/assets/images/p2.jpg",
    //   imageAlt:
    //     "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
    //   price: 29,
    //   color: "Iso Dots",
    //   rating: 3,
    //   numReviews: 23,
    //   countInStock: 7,
    //   slug: "adidas-fit-pant",
    // },
    // {
    //         name: "Gorno shoe",
    //   href: "#",
    //   imageSrc: "../src/assets/images/p3.jpg",
    //   imageAlt:
    //     "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
    //   price: 77,
    //   color: "Iso Dots",
    //   rating: 3,
    //   numReviews: 23,
    //   countInStock: 0,
    //   slug: "basic-tee",
    // },
    // {
    //         name: "Shirt 1",
    //   href: "#",
    //   imageSrc: "../src/assets/images/shirt1.png",
    //   imageAlt:
    //     "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
    //   price: 12,
    //   color: "Iso Dots",
    //   rating: 3,
    //   numReviews: 78,
    //   countInStock: 7,
    //   slug: "basic-tee",
    // },
    // {
    //         name: "Shirt 2",
    //   href: "#",
    //   imageSrc: "../src/assets/images/shirt2.png",
    //   imageAlt:
    //     "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
    //   price: 89,
    //   color: "Iso Dots",
    //   rating: 3,
    //   numReviews: 78,
    //   countInStock: 10,
    //   slug: "shirt-2",
    // },
    // {
    //   name: "Shirt 3",
    //   href: "#",
    //   imageSrc: "../src/assets/images/shirt3.png",
    //   imageAlt:
    //     "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
    //   price: 28,
    //   color: "Iso Dots",
    //   rating: 3,
    //   numReviews: 78,
    //   countInStock: 0,
    //   slug: "shirt-3",
    // },
    // {
    //   name: "Trouser 1",
    //   href: "#",
    //   imageSrc: "../src/assets/images/trouser1.png",
    //   imageAlt:
    //     "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
    //   price: 33,
    //   color: "Iso Dots",
    //   rating: 3,
    //   numReviews: 78,
    //   countInStock: 102,
    //   slug: "trouser-1",
    // },
    // {
    //   name: "Trouser 2",
    //   href: "#",
    //   imageSrc: "../src/assets/images/trouser2.png",
    //   imageAlt:
    //     "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
    //   price: 56,
    //   color: "Iso Dots",
    //   rating: 4,
    //   numReviews: 372,
    //   countInStock: 99,
    //   slug: "trouser-2",
    // },
    // {
    //   name: "Shirt 4",
    //   href: "#",
    //   imageSrc: "../src/assets/images/shirt4.png",
    //   imageAlt:
    //     "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
    //   price: 81,
    //   color: "Iso Dots",
    //   rating: 4,
    //   numReviews: 372,
    //   countInStock: 10,
    //   slug: "shirt-4",
    // },
    // {
    //   name: "p 4",
    //   href: "#",
    //   imageSrc: "../src/assets/images/p4.jpg",
    //   imageAlt:
    //     "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
    //   price: 19,
    //   color: "Iso Dots",
    //   rating: 4,
    //   numReviews: 372,
    //   countInStock: 0,
    //   slug: "p-4",
    // },
  ],
};

// const products = [
//   {
//     id: 1,
//     name: 'Basic Tee',
//     href: '#',
//     imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-01.jpg',
//     imageAlt: "Front of men's Basic Tee in black.",
//     price: '$35',
//     color: 'Black',
//   },
//   {
//     id: 2,
//     name: 'Basic Tee',
//     href: '#',
//     imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-02.jpg',
//     imageAlt: "Front of men's Basic Tee in white.",
//     price: '$35',
//     color: 'Aspen White',
//   },
//   {
//     id: 3,
//     name: 'Basic Tee',
//     href: '#',
//     imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-03.jpg',
//     imageAlt: "Front of men's Basic Tee in dark gray.",
//     price: '$35',
//     color: 'Charcoal',
//   },
//   {
//     id: 4,
//     name: 'Artwork Tee',
//     href: '#',
//     imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-04.jpg',
//     imageAlt: "Front of men's Artwork Tee in peach with white and brown dots forming an isometric cube.",
//     price: '$35',
//     color: 'Iso Dots',
//   },

export default data;
